In [2]:
import pandas as pd
import matplotlib.pyplot as plt
from scipy import stats
from scipy.stats import chi2_contingency

In [3]:
Click = [512 , 281, 527, 193]
No_click = [24814, 24466, 24349, 25040]

x =pd.DataFrame([Click , No_click], columns=['Version_A', 'Version_B', 'Version_C', 'Version_D'], index =('Click','No_click'))
x

          Version_A  Version_B  Version_C  Version_D
Click           512        281        527        193
No_click      24814      24466      24349      25040

In [15]:
alpha = 0.05/6 # using Bonferroni Adjustment
alpha

0.008333333333333333

For pairwise comparisons among n groups:

n(n-1)/2

So with 4 groups:

4(4-1)/2 = 6
Bonferroni Adjustment

In [5]:
chisq, pvalue, df, expected = stats.chi2_contingency(x)

In [6]:
#alternative
#chisq, pvalue, df, expected = chi2_contingency(x, correction=False)

In [7]:
chisq

np.float64(224.01877488058412)

In [8]:
pvalue

np.float64(2.7161216607868712e-48)

In [9]:
df

3

In [10]:
expected

array([[  382.48625502,   373.74189974,   375.69012397,   381.08172127],
       [24943.51374498, 24373.25810026, 24500.30987603, 24851.91827873]])

In [14]:
if pvalue < alpha:
  print("We Reject the Null Hypothesis")
else:
  print("We Fail to reject the Null Hypothesis")

We Reject the Null Hypothesis

In [12]:
# calculate the click through rate for each version
ctr_a = x.loc["Click", "Version_A"] / sum(x["Version_A"])
ctr_b = x.loc["Click", "Version_B"] / sum(x["Version_B"])
ctr_c = x.loc["Click", "Version_C"] / sum(x["Version_C"])
ctr_d = x.loc["Click", "Version_D"] / sum(x["Version_D"])

# create a table with all four versions and their click-through rates.
ctrs = pd.DataFrame(
    {"version": ["Version_A", "Version_B", "Version_C", "Version_D"], "CTR": [ctr_a, ctr_b, ctr_c, ctr_d]}
)

ctrs.sort_values("CTR", ascending=False)

     version       CTR
2  Version_C  0.021185
0  Version_A  0.020216
1  Version_B  0.011355
3  Version_D  0.007649

	•	CTR: C > A > B > D
	•	Drop-off: A > D > C
	•	Homepage-return: D > C > A

The overall chi-square test showed significant differences in CTR across the variants, but post-hoc testing did not identify a single winner based on CTR alone. After considering the additional behavioral metrics, Version A appears to be the best overall option. Although Version C has the highest CTR, it also has the highest drop-off rate, suggesting lower-quality engagement. Version A combines a strong CTR with the lowest drop-off rate, making it the most balanced choice.